name: Deploy to Render

on:
  push:
    branches: [ main ]  # Change this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}