name: Config Validation
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: grep -q "export const BOT_CONFIG" src/config/config.js || exit 1
